version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - mosquitto
networks:
  mosquitto:
    name: mosquitto
    driver: bridge